# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision :shell, :path => "vagrant/bootstrap.sh"

  config.vm.network "private_network", ip: "#{ENV['VAGRANT_IP_TRIPOD_TESTING']}"
  config.vm.hostname = "tripod-performance-testing.vagrant"
  config.vm.network "forwarded_port", guest: 27017, host: 27717
end
