FROM php:5.5-cli

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apt-get update && apt-get install -y git ca-certificates && \  
    chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pcntl redis mongodb-1.1.9 && \
    curl https://getcomposer.org/installer > /tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir /usr/local/bin/ --filename composer \
    && rm /tmp/composer-setup.php