FROM php:7.4.33-cli

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  unzip \
  zip \
  && rm -rf /var/lib/apt/lists/*

RUN curl -sLo /tmp/mongosh.deb https://downloads.mongodb.com/compass/mongodb-mongosh_2.2.15_amd64.deb \
  && dpkg -i /tmp/mongosh.deb \
  && rm /tmp/mongosh.deb

COPY --from=mlocati/php-extension-installer:2.3.2 /usr/bin/install-php-extensions /usr/local/bin/
COPY --from=composer:2.7.7 /usr/bin/composer /usr/local/bin/

RUN install-php-extensions pcntl mongodb-1.19.3
