FROM php:5.5-cli

# Debian jessie repositories have been moved to archive
# https://lists.debian.org/debian-devel-announce/2023/02/msg00004.html
RUN rm /etc/apt/sources.list && \
    echo 'deb [trusted=yes] http://archive.debian.org/debian-security jessie/updates main' >> /etc/apt/sources.list && \
    echo 'deb [trusted=yes] http://archive.debian.org/debian jessie main' >> /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' >> /etc/apt/apt.conf

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  unzip \
  zip \
  && rm -rf /var/lib/apt/lists/*

RUN curl -sLo - https://www.mongodb.org/static/pgp/server-3.6.asc | apt-key add - \
  && echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list \
  && apt-get update && apt-get install -y --no-install-recommends mongodb-org-shell --force-yes \
  && rm -rf /var/lib/apt/lists/*

COPY --from=mlocati/php-extension-installer:2.3.2 /usr/bin/install-php-extensions /usr/local/bin/
COPY --from=composer:2.2.20 /usr/bin/composer /usr/bin/composer

RUN install-php-extensions pcntl mongodb-1.5.5
