FROM php:7.2-cli

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pcntl redis mongodb-1.4.4 && \
    curl https://getcomposer.org/installer > /tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir /usr/local/bin/ --filename composer \
    && rm /tmp/composer-setup.php && \
    apt-get update && apt-get install -y git   