FROM php:7.3-cli

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  curl \
  git \
  unzip \
  zip \
  && rm -rf /var/lib/apt/lists/*

COPY --from=mlocati/php-extension-installer:2.1.58 /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions pcntl redis mongodb-1.5.5 && \
    curl https://getcomposer.org/installer >/tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir /usr/local/bin/ --filename composer && \
    rm /tmp/composer-setup.php
