<?php

declare(strict_types=1);

use Tripod\Config;
use Tripod\Exceptions\Exception;
use Tripod\Mongo\Driver;
use Tripod\Mongo\ImpactedSubject;

class ImpactedSubjectTest extends MongoTripodTestBase
{
    protected function setUp(): void
    {
        parent::setUp();
        $this->tripod = new Driver('CBD_testing', 'tripod_php_testing');
        $this->getTripodCollection($this->tripod)->drop();
        $this->loadResourceDataViaTripod();
    }

    public function testConstructorRejectsResourceIdWithoutRequiredKeys(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Parameter $resourceId needs to be of type array with ' . _ID_RESOURCE . ' and ' . _ID_CONTEXT . ' keys');

        new ImpactedSubject(['r' => 'http://example.com/1'], OP_VIEWS, 'tripod_php_testing', 'CBD_testing');
    }

    public function testConstructorRejectsNonStringResourceIdValues(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Parameter $resourceId needs to be of type array with ' . _ID_RESOURCE . ' and ' . _ID_CONTEXT . ' keys');

        new ImpactedSubject(['r' => 123, 'c' => 'http://talisaspire.com/'], OP_VIEWS, 'tripod_php_testing', 'CBD_testing');
    }

    public function testConstructorRejectsInvalidOperation(): void
    {
        $this->expectException(Exception::class);
        $this->expectExceptionMessage('Invalid operation: something_else');

        new ImpactedSubject(
            ['r' => 'http://example.com/1', 'c' => 'http://talisaspire.com/'],
            'something_else',
            'tripod_php_testing',
            'CBD_testing'
        );
    }

    public function testGettersReturnConstructorValues(): void
    {
        $stat = $this->getMockStat('example.com', 1234);
        $subject = new ImpactedSubject(
            ['r' => 'http://example.com/1', 'c' => 'http://talisaspire.com/'],
            OP_TABLES,
            'tripod_php_testing',
            'CBD_testing',
            ['t_resource'],
            $stat
        );

        $this->assertSame(['r' => 'http://example.com/1', 'c' => 'http://talisaspire.com/'], $subject->getResourceId());
        $this->assertSame(OP_TABLES, $subject->getOperation());
        $this->assertSame('tripod_php_testing', $subject->getStoreName());
        $this->assertSame('CBD_testing', $subject->getPodName());
        $this->assertSame(['t_resource'], $subject->getSpecTypes());
        $this->assertSame(
            [
                'resourceId' => ['r' => 'http://example.com/1', 'c' => 'http://talisaspire.com/'],
                'operation' => OP_TABLES,
                'specTypes' => ['t_resource'],
                'storeName' => 'tripod_php_testing',
                'podName' => 'CBD_testing',
            ],
            $subject->toArray()
        );
    }

    public function testUpdateRegeneratesTheComposite(): void
    {
        $stat = $this->getMockStat('example.com', 1234);
        $subject = new ImpactedSubject(
            ['r' => 'http://talisaspire.com/resources/3SplCtWGPqEyXcDiyhHQpA', 'c' => 'http://talisaspire.com/'],
            OP_TABLES,
            'tripod_php_testing',
            'CBD_testing',
            ['t_resource'],
            $stat
        );

        $subject->update();

        $collection = Config::getInstance()->getCollectionForTable('tripod_php_testing', 't_resource');
        $tableRow = $collection->findOne(['_id.type' => 't_resource', '_id.r' => 'http://talisaspire.com/resources/3SplCtWGPqEyXcDiyhHQpA']);
        $this->assertNotNull($tableRow, 'Expected a table row to have been generated by ImpactedSubject::update()');
    }
}
